# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis_status_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_analysisStatusDialog(object):
    def setupUi(self, analysisStatusDialog):
        analysisStatusDialog.setObjectName("analysisStatusDialog")
        analysisStatusDialog.resize(436, 443)
        self.gridLayout_3 = QtWidgets.QGridLayout(analysisStatusDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(analysisStatusDialog)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.transformation_in_progress = QtWidgets.QWidget()
        self.transformation_in_progress.setObjectName("transformation_in_progress")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.transformation_in_progress)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_cancel_analysis_process = QtWidgets.QPushButton(self.transformation_in_progress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel_analysis_process.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel_analysis_process.setSizePolicy(sizePolicy)
        self.pushButton_cancel_analysis_process.setAutoDefault(False)
        self.pushButton_cancel_analysis_process.setObjectName("pushButton_cancel_analysis_process")
        self.gridLayout_2.addWidget(self.pushButton_cancel_analysis_process, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 164, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.transformation_in_progress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(self.transformation_in_progress)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.label_analysis_status = QtWidgets.QLabel(self.transformation_in_progress)
        self.label_analysis_status.setEnabled(True)
        self.label_analysis_status.setText("")
        self.label_analysis_status.setScaledContents(True)
        self.label_analysis_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_analysis_status.setWordWrap(True)
        self.label_analysis_status.setObjectName("label_analysis_status")
        self.verticalLayout_3.addWidget(self.label_analysis_status)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.frame_preview_duration = QtWidgets.QFrame(self.transformation_in_progress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_preview_duration.sizePolicy().hasHeightForWidth())
        self.frame_preview_duration.setSizePolicy(sizePolicy)
        self.frame_preview_duration.setStyleSheet("background-color: rgb(155, 213, 254);")
        self.frame_preview_duration.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_preview_duration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preview_duration.setObjectName("frame_preview_duration")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_preview_duration)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.icon_preview_duration = QtWidgets.QLabel(self.frame_preview_duration)
        self.icon_preview_duration.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_preview_duration.setText("")
        self.icon_preview_duration.setPixmap(QtGui.QPixmap(":/analysis-status-dialog/ic_schedule_black_48dp.png"))
        self.icon_preview_duration.setScaledContents(True)
        self.icon_preview_duration.setWordWrap(True)
        self.icon_preview_duration.setObjectName("icon_preview_duration")
        self.horizontalLayout_3.addWidget(self.icon_preview_duration)
        self.label_preview_duration = QtWidgets.QLabel(self.frame_preview_duration)
        self.label_preview_duration.setWordWrap(True)
        self.label_preview_duration.setObjectName("label_preview_duration")
        self.horizontalLayout_3.addWidget(self.label_preview_duration)
        self.gridLayout_2.addWidget(self.frame_preview_duration, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.transformation_in_progress)
        self.label.setMaximumSize(QtCore.QSize(131, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/analysis-status-dialog/analysis_in_progress.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.transformation_in_progress)
        self.transformation_finished = QtWidgets.QWidget()
        self.transformation_finished.setObjectName("transformation_finished")
        self.gridLayout = QtWidgets.QGridLayout(self.transformation_finished)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox_close_status_dialog = QtWidgets.QDialogButtonBox(self.transformation_finished)
        self.buttonBox_close_status_dialog.setEnabled(True)
        self.buttonBox_close_status_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_close_status_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox_close_status_dialog.setObjectName("buttonBox_close_status_dialog")
        self.gridLayout.addWidget(self.buttonBox_close_status_dialog, 2, 0, 1, 3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.transformation_finished)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.progressBar_2 = QtWidgets.QProgressBar(self.transformation_finished)
        self.progressBar_2.setProperty("value", 100)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout.addWidget(self.progressBar_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.transformation_finished)
        self.label_6.setEnabled(True)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_analysis_duration = QtWidgets.QLabel(self.transformation_finished)
        self.label_analysis_duration.setObjectName("label_analysis_duration")
        self.horizontalLayout.addWidget(self.label_analysis_duration)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.groupBox_further_options = QtWidgets.QGroupBox(self.transformation_finished)
        self.groupBox_further_options.setObjectName("groupBox_further_options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_further_options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_statistics = QtWidgets.QPushButton(self.groupBox_further_options)
        self.pushButton_statistics.setObjectName("pushButton_statistics")
        self.verticalLayout_4.addWidget(self.pushButton_statistics)
        self.pushButton_technical_validation = QtWidgets.QPushButton(self.groupBox_further_options)
        self.pushButton_technical_validation.setObjectName("pushButton_technical_validation")
        self.verticalLayout_4.addWidget(self.pushButton_technical_validation)
        self.pushButton_html_previews = QtWidgets.QPushButton(self.groupBox_further_options)
        self.pushButton_html_previews.setObjectName("pushButton_html_previews")
        self.verticalLayout_4.addWidget(self.pushButton_html_previews)
        self.gridLayout.addWidget(self.groupBox_further_options, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.transformation_finished)
        self.label_5.setMaximumSize(QtCore.QSize(131, 131))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/analysis-status-dialog/analysis_finished.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.transformation_finished)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.frame_analysis_error = QtWidgets.QFrame(analysisStatusDialog)
        self.frame_analysis_error.setEnabled(True)
        self.frame_analysis_error.setStyleSheet("background-color: rgba(164, 219, 255, 235);")
        self.frame_analysis_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_analysis_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_analysis_error.setObjectName("frame_analysis_error")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_analysis_error)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_analysis_error = QtWidgets.QLabel(self.frame_analysis_error)
        self.icon_analysis_error.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_analysis_error.setText("")
        self.icon_analysis_error.setPixmap(QtGui.QPixmap(":/transformation-status-dialog/ic_info_black_48dp.png"))
        self.icon_analysis_error.setScaledContents(True)
        self.icon_analysis_error.setWordWrap(False)
        self.icon_analysis_error.setObjectName("icon_analysis_error")
        self.horizontalLayout_2.addWidget(self.icon_analysis_error)
        self.label_analysis_error = QtWidgets.QLabel(self.frame_analysis_error)
        self.label_analysis_error.setScaledContents(True)
        self.label_analysis_error.setWordWrap(True)
        self.label_analysis_error.setObjectName("label_analysis_error")
        self.horizontalLayout_2.addWidget(self.label_analysis_error)
        self.toolButton_analysis_error_show_log = QtWidgets.QToolButton(self.frame_analysis_error)
        self.toolButton_analysis_error_show_log.setAutoFillBackground(False)
        self.toolButton_analysis_error_show_log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolButton_analysis_error_show_log.setObjectName("toolButton_analysis_error_show_log")
        self.horizontalLayout_2.addWidget(self.toolButton_analysis_error_show_log)
        self.gridLayout_3.addWidget(self.frame_analysis_error, 1, 0, 1, 1)

        self.retranslateUi(analysisStatusDialog)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox_close_status_dialog.accepted.connect(analysisStatusDialog.accept)
        self.buttonBox_close_status_dialog.rejected.connect(analysisStatusDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(analysisStatusDialog)

    def retranslateUi(self, analysisStatusDialog):
        _translate = QtCore.QCoreApplication.translate
        analysisStatusDialog.setWindowTitle(_translate("analysisStatusDialog", "Analyse"))
        self.pushButton_cancel_analysis_process.setText(_translate("analysisStatusDialog", "Abbrechen"))
        self.label_2.setText(_translate("analysisStatusDialog", "Analyse läuft ..."))
        self.label_preview_duration.setText(_translate("analysisStatusDialog", "Wählen Sie die Option \"Testset automatisch ermitteln\", falls die Erstellung von Voransichten für alle Objekte lange andauert."))
        self.label_4.setText(_translate("analysisStatusDialog", "Analyse abgeschlossen."))
        self.label_6.setText(_translate("analysisStatusDialog", "Benötigte Zeit: "))
        self.label_analysis_duration.setText(_translate("analysisStatusDialog", "TextLabel"))
        self.groupBox_further_options.setTitle(_translate("analysisStatusDialog", "Analyseergebnisse verfügbar"))
        self.pushButton_statistics.setText(_translate("analysisStatusDialog", "Statistische Auswertung"))
        self.pushButton_technical_validation.setText(_translate("analysisStatusDialog", "Technische Validierung"))
        self.pushButton_html_previews.setText(_translate("analysisStatusDialog", "Voransichten"))
        self.label_analysis_error.setText(_translate("analysisStatusDialog", "Die Analyse konnte nicht vollständig durchgeführt werden."))
        self.toolButton_analysis_error_show_log.setText(_translate("analysisStatusDialog", "Logdatei anzeigen"))

from gui_components.ui_templates import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    analysisStatusDialog = QtWidgets.QDialog()
    ui = Ui_analysisStatusDialog()
    ui.setupUi(analysisStatusDialog)
    analysisStatusDialog.show()
    sys.exit(app.exec_())

