# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapping_definition_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mappingDefinitionDialog(object):
    def setupUi(self, mappingDefinitionDialog):
        mappingDefinitionDialog.setObjectName("mappingDefinitionDialog")
        mappingDefinitionDialog.resize(865, 685)
        self.gridLayout = QtWidgets.QGridLayout(mappingDefinitionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(mappingDefinitionDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(mappingDefinitionDialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(mappingDefinitionDialog)
        self.label_3.setMaximumSize(QtCore.QSize(25, 25))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/mapping-definition-dialog/info_icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(324, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(mappingDefinitionDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(mappingDefinitionDialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(mappingDefinitionDialog)
        self.label_4.setMaximumSize(QtCore.QSize(25, 25))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/mapping-definition-dialog/info_icon.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(mappingDefinitionDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mappingTableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.mappingTableWidget.setObjectName("mappingTableWidget")
        self.mappingTableWidget.setColumnCount(6)
        self.mappingTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(188, 215, 179))
        self.mappingTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(188, 215, 179))
        self.mappingTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(249, 213, 178))
        self.mappingTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(142, 169, 198))
        self.mappingTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(142, 169, 198))
        self.mappingTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(142, 169, 198))
        self.mappingTableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_2.addWidget(self.mappingTableWidget, 0, 0, 1, 2)
        self.pushButton_add_row = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mapping-definition-dialog/library-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_row.setIcon(icon)
        self.pushButton_add_row.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_add_row.setObjectName("pushButton_add_row")
        self.gridLayout_2.addWidget(self.pushButton_add_row, 1, 0, 1, 1)
        self.pushButton_delete_row = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/mapping-definition-dialog/table-row-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete_row.setIcon(icon1)
        self.pushButton_delete_row.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_delete_row.setObjectName("pushButton_delete_row")
        self.gridLayout_2.addWidget(self.pushButton_delete_row, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 7)
        self.buttonBox = QtWidgets.QDialogButtonBox(mappingDefinitionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 5, 1, 2)

        self.retranslateUi(mappingDefinitionDialog)
        self.buttonBox.accepted.connect(mappingDefinitionDialog.accept)
        self.buttonBox.rejected.connect(mappingDefinitionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(mappingDefinitionDialog)

    def retranslateUi(self, mappingDefinitionDialog):
        _translate = QtCore.QCoreApplication.translate
        mappingDefinitionDialog.setWindowTitle(_translate("mappingDefinitionDialog", "Mappingzuordnung bearbeiten"))
        self.label.setText(_translate("mappingDefinitionDialog", "Quellformat:"))
        self.comboBox.setItemText(0, _translate("mappingDefinitionDialog", "EAD2002"))
        self.comboBox.setItemText(1, _translate("mappingDefinitionDialog", "EAD 3.0"))
        self.comboBox.setItemText(2, _translate("mappingDefinitionDialog", "Excel / csv"))
        self.comboBox.setItemText(3, _translate("mappingDefinitionDialog", "SQL"))
        self.label_3.setToolTip(_translate("mappingDefinitionDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Das Quellformat bezeichnet den Typ der Eingangsdatei und damit auch die beim Mapping zur Verfügung stehenden Elemente.</span></p><p>Hinweis: Sollten sie dieses Tool von der DDB-Fachstelle Archiv erhalten haben, so ist das korrekte Quell- bzw. Zielformat in der Regel bereits vorausgewählt.</p></body></html>"))
        self.label_2.setText(_translate("mappingDefinitionDialog", "Zielformat:"))
        self.comboBox_2.setItemText(0, _translate("mappingDefinitionDialog", "EAD(DDB)"))
        self.comboBox_2.setItemText(1, _translate("mappingDefinitionDialog", "LeoBW SimpleXML"))
        self.label_4.setToolTip(_translate("mappingDefinitionDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Das Zielformat bestimmt die Form, in der die zugeordneten Quelldaten ausgegeben werden. Analog zum Quellformat wird hierdurch bestimmt, auf welche Zielemente die Feldinhalte überführt werden können.</span></p><p>Hinweis: Sollten sie dieses Tool von der DDB-Fachstelle Archiv erhalten haben, so ist das korrekte Quell- bzw. Zielformat in der Regel bereits vorausgewählt.</p></body></html>"))
        self.groupBox.setTitle(_translate("mappingDefinitionDialog", "Feldzuordnung nach Ebene"))
        item = self.mappingTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mappingDefinitionDialog", "Element (Quelle)"))
        item = self.mappingTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mappingDefinitionDialog", "Attribut (Quelle)"))
        item = self.mappingTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mappingDefinitionDialog", "Ebene"))
        item = self.mappingTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mappingDefinitionDialog", "Element (Ziel)"))
        item = self.mappingTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mappingDefinitionDialog", "Attribut (Ziel)"))
        item = self.mappingTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mappingDefinitionDialog", "Präfix (Ziel)"))
        self.pushButton_add_row.setText(_translate("mappingDefinitionDialog", "Zeile hinzufügen"))
        self.pushButton_delete_row.setText(_translate("mappingDefinitionDialog", "Ausgewählte Zeile löschen"))

from gui_components.ui_templates import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mappingDefinitionDialog = QtWidgets.QDialog()
    ui = Ui_mappingDefinitionDialog()
    ui.setupUi(mappingDefinitionDialog)
    mappingDefinitionDialog.show()
    sys.exit(app.exec_())

