# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'provider_scripts_configure_maintenance_function_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_providerScriptsConfigureMaintenanceFunctionDialog(object):
    def setupUi(self, providerScriptsConfigureMaintenanceFunctionDialog):
        providerScriptsConfigureMaintenanceFunctionDialog.setObjectName("providerScriptsConfigureMaintenanceFunctionDialog")
        providerScriptsConfigureMaintenanceFunctionDialog.resize(337, 177)
        providerScriptsConfigureMaintenanceFunctionDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(providerScriptsConfigureMaintenanceFunctionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(providerScriptsConfigureMaintenanceFunctionDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_choose_maintenance_function = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_choose_maintenance_function.setObjectName("comboBox_choose_maintenance_function")
        self.comboBox_choose_maintenance_function.addItem("")
        self.comboBox_choose_maintenance_function.addItem("")
        self.comboBox_choose_maintenance_function.addItem("")
        self.comboBox_choose_maintenance_function.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_choose_maintenance_function, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("background-color: rgba(164, 219, 255, 235);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_maintenance_function_info = QtWidgets.QLabel(self.frame)
        self.label_maintenance_function_info.setScaledContents(True)
        self.label_maintenance_function_info.setWordWrap(True)
        self.label_maintenance_function_info.setObjectName("label_maintenance_function_info")
        self.gridLayout_3.addWidget(self.label_maintenance_function_info, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox_providerscripts_maintenance_configuration = QtWidgets.QDialogButtonBox(providerScriptsConfigureMaintenanceFunctionDialog)
        self.buttonBox_providerscripts_maintenance_configuration.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_providerscripts_maintenance_configuration.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_providerscripts_maintenance_configuration.setObjectName("buttonBox_providerscripts_maintenance_configuration")
        self.gridLayout.addWidget(self.buttonBox_providerscripts_maintenance_configuration, 1, 0, 1, 1)

        self.retranslateUi(providerScriptsConfigureMaintenanceFunctionDialog)
        self.buttonBox_providerscripts_maintenance_configuration.accepted.connect(providerScriptsConfigureMaintenanceFunctionDialog.accept)
        self.buttonBox_providerscripts_maintenance_configuration.rejected.connect(providerScriptsConfigureMaintenanceFunctionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(providerScriptsConfigureMaintenanceFunctionDialog)

    def retranslateUi(self, providerScriptsConfigureMaintenanceFunctionDialog):
        _translate = QtCore.QCoreApplication.translate
        providerScriptsConfigureMaintenanceFunctionDialog.setWindowTitle(_translate("providerScriptsConfigureMaintenanceFunctionDialog", "Vorprozessierungsschritt konfigurieren"))
        self.groupBox.setTitle(_translate("providerScriptsConfigureMaintenanceFunctionDialog", "Art der Vorprozessierung wählen"))
        self.comboBox_choose_maintenance_function.setItemText(0, _translate("providerScriptsConfigureMaintenanceFunctionDialog", "Rechte/Lizenz-Anreicherung"))
        self.comboBox_choose_maintenance_function.setItemText(1, _translate("providerScriptsConfigureMaintenanceFunctionDialog", "DDB-2017-Vorprozessierung"))
        self.comboBox_choose_maintenance_function.setItemText(2, _translate("providerScriptsConfigureMaintenanceFunctionDialog", "Aggregator-Anreicherung"))
        self.comboBox_choose_maintenance_function.setItemText(3, _translate("providerScriptsConfigureMaintenanceFunctionDialog", "Mapping-Definition anwenden"))
        self.label_maintenance_function_info.setText(_translate("providerScriptsConfigureMaintenanceFunctionDialog", "Die gewählte Vorprozessierung kann im Menü \"Tools\" des Hauptfensters weiter konfiguriert werden."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    providerScriptsConfigureMaintenanceFunctionDialog = QtWidgets.QDialog()
    ui = Ui_providerScriptsConfigureMaintenanceFunctionDialog()
    ui.setupUi(providerScriptsConfigureMaintenanceFunctionDialog)
    providerScriptsConfigureMaintenanceFunctionDialog.show()
    sys.exit(app.exec_())
