# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'provider_metadata_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_providerMetadataDialog(object):
    def setupUi(self, providerMetadataDialog):
        providerMetadataDialog.setObjectName("providerMetadataDialog")
        providerMetadataDialog.resize(460, 570)
        providerMetadataDialog.setMinimumSize(QtCore.QSize(460, 570))
        providerMetadataDialog.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(providerMetadataDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_software = QtWidgets.QLabel(providerMetadataDialog)
        self.label_software.setScaledContents(True)
        self.label_software.setObjectName("label_software")
        self.gridLayout_2.addWidget(self.label_software, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.buttonBox_provider_metadata = QtWidgets.QDialogButtonBox(providerMetadataDialog)
        self.buttonBox_provider_metadata.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_provider_metadata.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_provider_metadata.setObjectName("buttonBox_provider_metadata")
        self.gridLayout_2.addWidget(self.buttonBox_provider_metadata, 9, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.comboBox_softwaremode = QtWidgets.QComboBox(providerMetadataDialog)
        self.comboBox_softwaremode.setEnabled(False)
        self.comboBox_softwaremode.setObjectName("comboBox_softwaremode")
        self.comboBox_softwaremode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_softwaremode, 8, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.lineEdit_provider_id = QtWidgets.QLineEdit(providerMetadataDialog)
        self.lineEdit_provider_id.setObjectName("lineEdit_provider_id")
        self.gridLayout_2.addWidget(self.lineEdit_provider_id, 3, 2, 1, 1)
        self.lineEdit_provider_tektonik_url = QtWidgets.QLineEdit(providerMetadataDialog)
        self.lineEdit_provider_tektonik_url.setObjectName("lineEdit_provider_tektonik_url")
        self.gridLayout_2.addWidget(self.lineEdit_provider_tektonik_url, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(providerMetadataDialog)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_provider_name = QtWidgets.QLineEdit(providerMetadataDialog)
        self.lineEdit_provider_name.setObjectName("lineEdit_provider_name")
        self.gridLayout_2.addWidget(self.lineEdit_provider_name, 0, 2, 1, 1)
        self.comboBox_provider_archivtyp = QtWidgets.QComboBox(providerMetadataDialog)
        self.comboBox_provider_archivtyp.setObjectName("comboBox_provider_archivtyp")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.comboBox_provider_archivtyp.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_provider_archivtyp, 5, 2, 1, 1)
        self.lineEdit_provider_isil = QtWidgets.QLineEdit(providerMetadataDialog)
        self.lineEdit_provider_isil.setReadOnly(True)
        self.lineEdit_provider_isil.setObjectName("lineEdit_provider_isil")
        self.gridLayout_2.addWidget(self.lineEdit_provider_isil, 2, 2, 1, 1)
        self.lineEdit_provider_website = QtWidgets.QLineEdit(providerMetadataDialog)
        self.lineEdit_provider_website.setObjectName("lineEdit_provider_website")
        self.gridLayout_2.addWidget(self.lineEdit_provider_website, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(providerMetadataDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_provider_addressline_strasse = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_provider_addressline_strasse.setObjectName("lineEdit_provider_addressline_strasse")
        self.gridLayout.addWidget(self.lineEdit_provider_addressline_strasse, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_provider_addressline_ort = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_provider_addressline_ort.setObjectName("lineEdit_provider_addressline_ort")
        self.gridLayout.addWidget(self.lineEdit_provider_addressline_ort, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_provider_addressline_mail = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_provider_addressline_mail.setObjectName("lineEdit_provider_addressline_mail")
        self.gridLayout.addWidget(self.lineEdit_provider_addressline_mail, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.comboBox_provider_state = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_provider_state.setObjectName("comboBox_provider_state")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.comboBox_provider_state.addItem("")
        self.gridLayout.addWidget(self.comboBox_provider_state, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 7, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_5.setMaximumSize(QtCore.QSize(25, 25))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/provider-metadata-dialog/info_icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(providerMetadataDialog)
        self.label_7.setMaximumSize(QtCore.QSize(25, 25))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/provider-metadata-dialog/info_icon.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 3, 1, 1)

        self.retranslateUi(providerMetadataDialog)
        self.comboBox_softwaremode.setCurrentIndex(0)
        self.buttonBox_provider_metadata.accepted.connect(providerMetadataDialog.accept)
        self.buttonBox_provider_metadata.rejected.connect(providerMetadataDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(providerMetadataDialog)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_name, self.lineEdit_provider_website)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_website, self.lineEdit_provider_isil)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_isil, self.lineEdit_provider_id)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_id, self.lineEdit_provider_tektonik_url)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_tektonik_url, self.comboBox_provider_archivtyp)
        providerMetadataDialog.setTabOrder(self.comboBox_provider_archivtyp, self.lineEdit_provider_addressline_strasse)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_addressline_strasse, self.lineEdit_provider_addressline_ort)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_addressline_ort, self.lineEdit_provider_addressline_mail)
        providerMetadataDialog.setTabOrder(self.lineEdit_provider_addressline_mail, self.comboBox_provider_state)
        providerMetadataDialog.setTabOrder(self.comboBox_provider_state, self.comboBox_softwaremode)

    def retranslateUi(self, providerMetadataDialog):
        _translate = QtCore.QCoreApplication.translate
        providerMetadataDialog.setWindowTitle(_translate("providerMetadataDialog", "Archiv-Metadaten bearbeiten"))
        self.label_software.setText(_translate("providerMetadataDialog", "Softwaremodus:"))
        self.label_2.setText(_translate("providerMetadataDialog", "URL zur Website des Archivs:"))
        self.label_3.setToolTip(_translate("providerMetadataDialog", "Durch Datengeber-Auswahl vorgegeben."))
        self.label_3.setText(_translate("providerMetadataDialog", "ISIL des Archivs:"))
        self.comboBox_softwaremode.setItemText(0, _translate("providerMetadataDialog", "eadddb"))
        self.label_14.setText(_translate("providerMetadataDialog", "Archivsparte:"))
        self.label_4.setToolTip(_translate("providerMetadataDialog", "Bei der Provider-ID handelt es sich um einen DDB-internen Identifier. Dieser ist optional und muss nicht zwingend angegeben werden."))
        self.label_4.setText(_translate("providerMetadataDialog", "Provider-ID des Archivs:"))
        self.label_6.setText(_translate("providerMetadataDialog", "URL zur Tektonik des Archivs:"))
        self.lineEdit_provider_id.setToolTip(_translate("providerMetadataDialog", "Bei der Provider-ID handelt es sich um einen DDB-internen Identifier. Dieser ist optional und muss nicht zwingend angegeben werden."))
        self.label.setText(_translate("providerMetadataDialog", "Name des Archivs:"))
        self.comboBox_provider_archivtyp.setItemText(0, _translate("providerMetadataDialog", "Staatliche Archive"))
        self.comboBox_provider_archivtyp.setItemText(1, _translate("providerMetadataDialog", "Kommunale Archive"))
        self.comboBox_provider_archivtyp.setItemText(2, _translate("providerMetadataDialog", "Kirchliche Archive"))
        self.comboBox_provider_archivtyp.setItemText(3, _translate("providerMetadataDialog", "Herrschafts- und Familienarchive"))
        self.comboBox_provider_archivtyp.setItemText(4, _translate("providerMetadataDialog", "Wirtschaftsarchive"))
        self.comboBox_provider_archivtyp.setItemText(5, _translate("providerMetadataDialog", "Archive der Parlamente, politischen Parteien, Stiftung und Verbände"))
        self.comboBox_provider_archivtyp.setItemText(6, _translate("providerMetadataDialog", "Medienarchive"))
        self.comboBox_provider_archivtyp.setItemText(7, _translate("providerMetadataDialog", "Archive der Hochschulen sowie wissenschaftlicher Institutionen"))
        self.comboBox_provider_archivtyp.setItemText(8, _translate("providerMetadataDialog", "Sonstige Archive"))
        self.lineEdit_provider_isil.setToolTip(_translate("providerMetadataDialog", "Durch Datengeber-Auswahl vorgegeben."))
        self.groupBox.setTitle(_translate("providerMetadataDialog", "Adressdaten"))
        self.label_8.setText(_translate("providerMetadataDialog", "Straße:"))
        self.lineEdit_provider_addressline_strasse.setPlaceholderText(_translate("providerMetadataDialog", "z.B.: Testgasse 1"))
        self.label_10.setText(_translate("providerMetadataDialog", "Ort:"))
        self.lineEdit_provider_addressline_ort.setPlaceholderText(_translate("providerMetadataDialog", "z.B.: D - 76137 Karlsruhe"))
        self.label_12.setText(_translate("providerMetadataDialog", "E-Mail: "))
        self.lineEdit_provider_addressline_mail.setPlaceholderText(_translate("providerMetadataDialog", "z.B.: test@archiv.de"))
        self.label_15.setText(_translate("providerMetadataDialog", "Bundesland:"))
        self.comboBox_provider_state.setItemText(0, _translate("providerMetadataDialog", "Baden-Württemberg"))
        self.comboBox_provider_state.setItemText(1, _translate("providerMetadataDialog", "Bayern"))
        self.comboBox_provider_state.setItemText(2, _translate("providerMetadataDialog", "Berlin"))
        self.comboBox_provider_state.setItemText(3, _translate("providerMetadataDialog", "Brandenburg"))
        self.comboBox_provider_state.setItemText(4, _translate("providerMetadataDialog", "Bremen"))
        self.comboBox_provider_state.setItemText(5, _translate("providerMetadataDialog", "Hamburg"))
        self.comboBox_provider_state.setItemText(6, _translate("providerMetadataDialog", "Hessen"))
        self.comboBox_provider_state.setItemText(7, _translate("providerMetadataDialog", "Mecklenburg-Vorpommern"))
        self.comboBox_provider_state.setItemText(8, _translate("providerMetadataDialog", "Niedersachsen"))
        self.comboBox_provider_state.setItemText(9, _translate("providerMetadataDialog", "Nordrhein-Westfalen"))
        self.comboBox_provider_state.setItemText(10, _translate("providerMetadataDialog", "Rheinland-Pfalz"))
        self.comboBox_provider_state.setItemText(11, _translate("providerMetadataDialog", "Saarland"))
        self.comboBox_provider_state.setItemText(12, _translate("providerMetadataDialog", "Sachsen"))
        self.comboBox_provider_state.setItemText(13, _translate("providerMetadataDialog", "Sachsen-Anhalt"))
        self.comboBox_provider_state.setItemText(14, _translate("providerMetadataDialog", "Schleswig-Holstein"))
        self.comboBox_provider_state.setItemText(15, _translate("providerMetadataDialog", "Thüringen"))
        self.label_5.setToolTip(_translate("providerMetadataDialog", "Durch Datengeber-Auswahl vorgegeben."))
        self.label_7.setToolTip(_translate("providerMetadataDialog", "Bei der Provider-ID handelt es sich um einen DDB-internen Identifier. Dieser ist optional und muss nicht zwingend angegeben werden."))

from gui_components.ui_templates import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    providerMetadataDialog = QtWidgets.QDialog()
    ui = Ui_providerMetadataDialog()
    ui.setupUi(providerMetadataDialog)
    providerMetadataDialog.show()
    sys.exit(app.exec_())

