# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'provider_scripts_configure_user_interaction_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_providerScriptsConfigureUserInteractionDialog(object):
    def setupUi(self, providerScriptsConfigureUserInteractionDialog):
        providerScriptsConfigureUserInteractionDialog.setObjectName("providerScriptsConfigureUserInteractionDialog")
        providerScriptsConfigureUserInteractionDialog.resize(400, 317)
        providerScriptsConfigureUserInteractionDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(providerScriptsConfigureUserInteractionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(providerScriptsConfigureUserInteractionDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_providerscript_user_interaction_filename = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_providerscript_user_interaction_filename.setObjectName("lineEdit_providerscript_user_interaction_filename")
        self.gridLayout_2.addWidget(self.lineEdit_providerscript_user_interaction_filename, 1, 0, 1, 1)
        self.checkBox_providerscript_user_interaction_include_all_files = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_providerscript_user_interaction_include_all_files.setEnabled(False)
        self.checkBox_providerscript_user_interaction_include_all_files.setObjectName("checkBox_providerscript_user_interaction_include_all_files")
        self.gridLayout_2.addWidget(self.checkBox_providerscript_user_interaction_include_all_files, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.plainTextEdit_providerscript_user_interaction_description = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_providerscript_user_interaction_description.setObjectName("plainTextEdit_providerscript_user_interaction_description")
        self.gridLayout_2.addWidget(self.plainTextEdit_providerscript_user_interaction_description, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox_providerscripts_user_interaction_configuration = QtWidgets.QDialogButtonBox(providerScriptsConfigureUserInteractionDialog)
        self.buttonBox_providerscripts_user_interaction_configuration.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_providerscripts_user_interaction_configuration.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_providerscripts_user_interaction_configuration.setObjectName("buttonBox_providerscripts_user_interaction_configuration")
        self.gridLayout.addWidget(self.buttonBox_providerscripts_user_interaction_configuration, 1, 0, 1, 1)

        self.retranslateUi(providerScriptsConfigureUserInteractionDialog)
        self.buttonBox_providerscripts_user_interaction_configuration.accepted.connect(providerScriptsConfigureUserInteractionDialog.accept)
        self.buttonBox_providerscripts_user_interaction_configuration.rejected.connect(providerScriptsConfigureUserInteractionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(providerScriptsConfigureUserInteractionDialog)

    def retranslateUi(self, providerScriptsConfigureUserInteractionDialog):
        _translate = QtCore.QCoreApplication.translate
        providerScriptsConfigureUserInteractionDialog.setWindowTitle(_translate("providerScriptsConfigureUserInteractionDialog", "Nutzerinteraktion konfigurieren"))
        self.groupBox.setTitle(_translate("providerScriptsConfigureUserInteractionDialog", "Angaben zur Nutzerinteraktion"))
        self.label.setText(_translate("providerScriptsConfigureUserInteractionDialog", "Dateiname:"))
        self.lineEdit_providerscript_user_interaction_filename.setPlaceholderText(_translate("providerScriptsConfigureUserInteractionDialog", "z.B.: findbuch.xml | findb* | *buch.xml"))
        self.checkBox_providerscript_user_interaction_include_all_files.setToolTip(_translate("providerScriptsConfigureUserInteractionDialog", "Diese Funktionalität wird in einer späteren Version umgesetzt."))
        self.checkBox_providerscript_user_interaction_include_all_files.setText(_translate("providerScriptsConfigureUserInteractionDialog", "alle Dateien einschließen"))
        self.label_2.setText(_translate("providerScriptsConfigureUserInteractionDialog", "Beschreibung:"))
        self.plainTextEdit_providerscript_user_interaction_description.setPlaceholderText(_translate("providerScriptsConfigureUserInteractionDialog", "Hier kann ein Beschreibungstext mit Hinweisen zur manuellen Bearbeitung hinterlegt werden."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    providerScriptsConfigureUserInteractionDialog = QtWidgets.QDialog()
    ui = Ui_providerScriptsConfigureUserInteractionDialog()
    ui.setupUi(providerScriptsConfigureUserInteractionDialog)
    providerScriptsConfigureUserInteractionDialog.show()
    sys.exit(app.exec_())
