# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transformation_status_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_transformationStatusDialog(object):
    def setupUi(self, transformationStatusDialog):
        transformationStatusDialog.setObjectName("transformationStatusDialog")
        transformationStatusDialog.resize(436, 422)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(transformationStatusDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(transformationStatusDialog)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.transformation_in_progress = QtWidgets.QWidget()
        self.transformation_in_progress.setObjectName("transformation_in_progress")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.transformation_in_progress)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.transformation_in_progress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(self.transformation_in_progress)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.label_transformation_status = QtWidgets.QLabel(self.transformation_in_progress)
        self.label_transformation_status.setEnabled(True)
        self.label_transformation_status.setText("")
        self.label_transformation_status.setScaledContents(True)
        self.label_transformation_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_transformation_status.setWordWrap(True)
        self.label_transformation_status.setObjectName("label_transformation_status")
        self.verticalLayout_3.addWidget(self.label_transformation_status)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.transformation_in_progress)
        self.label.setMaximumSize(QtCore.QSize(131, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/transformation-status-dialog/transformation_in_progress.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_cancel_transformation_process = QtWidgets.QPushButton(self.transformation_in_progress)
        self.pushButton_cancel_transformation_process.setAutoDefault(False)
        self.pushButton_cancel_transformation_process.setObjectName("pushButton_cancel_transformation_process")
        self.gridLayout_2.addWidget(self.pushButton_cancel_transformation_process, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.transformation_in_progress)
        self.transformation_finished = QtWidgets.QWidget()
        self.transformation_finished.setObjectName("transformation_finished")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.transformation_finished)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.transformation_finished)
        self.label_5.setMaximumSize(QtCore.QSize(131, 131))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/transformation-status-dialog/transformation_finished.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.transformation_finished)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.progressBar_2 = QtWidgets.QProgressBar(self.transformation_finished)
        self.progressBar_2.setProperty("value", 100)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout.addWidget(self.progressBar_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.transformation_finished)
        self.label_6.setEnabled(True)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_transformation_duration = QtWidgets.QLabel(self.transformation_finished)
        self.label_transformation_duration.setObjectName("label_transformation_duration")
        self.horizontalLayout.addWidget(self.label_transformation_duration)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_further_options = QtWidgets.QGroupBox(self.transformation_finished)
        self.groupBox_further_options.setObjectName("groupBox_further_options")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_further_options)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_analysis_after_transformation = QtWidgets.QPushButton(self.groupBox_further_options)
        self.pushButton_analysis_after_transformation.setObjectName("pushButton_analysis_after_transformation")
        self.gridLayout.addWidget(self.pushButton_analysis_after_transformation, 0, 0, 1, 1)
        self.pushButton_open_transformation_output = QtWidgets.QPushButton(self.groupBox_further_options)
        self.pushButton_open_transformation_output.setObjectName("pushButton_open_transformation_output")
        self.gridLayout.addWidget(self.pushButton_open_transformation_output, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_further_options, 0, 0, 1, 1)
        self.buttonBox_close_status_dialog = QtWidgets.QDialogButtonBox(self.transformation_finished)
        self.buttonBox_close_status_dialog.setEnabled(True)
        self.buttonBox_close_status_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_close_status_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox_close_status_dialog.setObjectName("buttonBox_close_status_dialog")
        self.gridLayout_4.addWidget(self.buttonBox_close_status_dialog, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.transformation_finished)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.frame_transformation_error = QtWidgets.QFrame(transformationStatusDialog)
        self.frame_transformation_error.setEnabled(True)
        self.frame_transformation_error.setStyleSheet("background-color: rgba(164, 219, 255, 235);")
        self.frame_transformation_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_transformation_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_transformation_error.setObjectName("frame_transformation_error")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_transformation_error)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_transformation_error = QtWidgets.QLabel(self.frame_transformation_error)
        self.icon_transformation_error.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_transformation_error.setText("")
        self.icon_transformation_error.setPixmap(QtGui.QPixmap(":/transformation-status-dialog/ic_info_black_48dp.png"))
        self.icon_transformation_error.setScaledContents(True)
        self.icon_transformation_error.setWordWrap(False)
        self.icon_transformation_error.setObjectName("icon_transformation_error")
        self.horizontalLayout_2.addWidget(self.icon_transformation_error)
        self.label_transformation_error = QtWidgets.QLabel(self.frame_transformation_error)
        self.label_transformation_error.setScaledContents(True)
        self.label_transformation_error.setWordWrap(True)
        self.label_transformation_error.setObjectName("label_transformation_error")
        self.horizontalLayout_2.addWidget(self.label_transformation_error)
        self.toolButton_transformation_error_show_log = QtWidgets.QToolButton(self.frame_transformation_error)
        self.toolButton_transformation_error_show_log.setAutoFillBackground(False)
        self.toolButton_transformation_error_show_log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolButton_transformation_error_show_log.setObjectName("toolButton_transformation_error_show_log")
        self.horizontalLayout_2.addWidget(self.toolButton_transformation_error_show_log)
        self.verticalLayout_4.addWidget(self.frame_transformation_error)

        self.retranslateUi(transformationStatusDialog)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox_close_status_dialog.accepted.connect(transformationStatusDialog.accept)
        self.buttonBox_close_status_dialog.rejected.connect(transformationStatusDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(transformationStatusDialog)

    def retranslateUi(self, transformationStatusDialog):
        _translate = QtCore.QCoreApplication.translate
        transformationStatusDialog.setWindowTitle(_translate("transformationStatusDialog", "Transformation"))
        self.label_2.setText(_translate("transformationStatusDialog", "Transformation läuft ..."))
        self.pushButton_cancel_transformation_process.setText(_translate("transformationStatusDialog", "Abbrechen"))
        self.label_4.setText(_translate("transformationStatusDialog", "Transformation abgeschlossen."))
        self.label_6.setText(_translate("transformationStatusDialog", "Benötigte Zeit: "))
        self.label_transformation_duration.setText(_translate("transformationStatusDialog", "TextLabel"))
        self.groupBox_further_options.setTitle(_translate("transformationStatusDialog", "Weiterführende Optionen"))
        self.pushButton_analysis_after_transformation.setText(_translate("transformationStatusDialog", "Analyse starten"))
        self.pushButton_open_transformation_output.setText(_translate("transformationStatusDialog", "Ausgabe-Ordner öffnen"))
        self.label_transformation_error.setText(_translate("transformationStatusDialog", "Die Transformation konnte nicht vollständig durchgeführt werden."))
        self.toolButton_transformation_error_show_log.setText(_translate("transformationStatusDialog", "Logdatei anzeigen"))

from gui_components.ui_templates import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transformationStatusDialog = QtWidgets.QDialog()
    ui = Ui_transformationStatusDialog()
    ui.setupUi(transformationStatusDialog)
    transformationStatusDialog.show()
    sys.exit(app.exec_())

