# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'validation_status_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_validationStatusDialog(object):
    def setupUi(self, validationStatusDialog):
        validationStatusDialog.setObjectName("validationStatusDialog")
        validationStatusDialog.resize(436, 443)
        self.gridLayout_3 = QtWidgets.QGridLayout(validationStatusDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(validationStatusDialog)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.validation_in_progress = QtWidgets.QWidget()
        self.validation_in_progress.setObjectName("validation_in_progress")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.validation_in_progress)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 164, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.validation_in_progress)
        self.label.setMaximumSize(QtCore.QSize(131, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/analysis-status-dialog/analysis_in_progress.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.validation_in_progress)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(self.validation_in_progress)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.label_validation_status = QtWidgets.QLabel(self.validation_in_progress)
        self.label_validation_status.setEnabled(True)
        self.label_validation_status.setText("")
        self.label_validation_status.setScaledContents(True)
        self.label_validation_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_validation_status.setWordWrap(True)
        self.label_validation_status.setObjectName("label_validation_status")
        self.verticalLayout_3.addWidget(self.label_validation_status)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.pushButton_cancel_validation_process = QtWidgets.QPushButton(self.validation_in_progress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel_validation_process.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel_validation_process.setSizePolicy(sizePolicy)
        self.pushButton_cancel_validation_process.setAutoDefault(False)
        self.pushButton_cancel_validation_process.setObjectName("pushButton_cancel_validation_process")
        self.gridLayout_2.addWidget(self.pushButton_cancel_validation_process, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.validation_in_progress)
        self.validation_finished = QtWidgets.QWidget()
        self.validation_finished.setObjectName("validation_finished")
        self.gridLayout = QtWidgets.QGridLayout(self.validation_finished)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox_close_status_dialog = QtWidgets.QDialogButtonBox(self.validation_finished)
        self.buttonBox_close_status_dialog.setEnabled(True)
        self.buttonBox_close_status_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_close_status_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox_close_status_dialog.setObjectName("buttonBox_close_status_dialog")
        self.gridLayout.addWidget(self.buttonBox_close_status_dialog, 2, 0, 1, 3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.validation_finished)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.progressBar_2 = QtWidgets.QProgressBar(self.validation_finished)
        self.progressBar_2.setProperty("value", 100)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout.addWidget(self.progressBar_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.validation_finished)
        self.label_6.setEnabled(True)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_validation_duration = QtWidgets.QLabel(self.validation_finished)
        self.label_validation_duration.setObjectName("label_validation_duration")
        self.horizontalLayout.addWidget(self.label_validation_duration)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.groupBox_further_options = QtWidgets.QGroupBox(self.validation_finished)
        self.groupBox_further_options.setObjectName("groupBox_further_options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_further_options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_open_validation_results = QtWidgets.QPushButton(self.groupBox_further_options)
        self.pushButton_open_validation_results.setObjectName("pushButton_open_validation_results")
        self.verticalLayout_4.addWidget(self.pushButton_open_validation_results)
        self.gridLayout.addWidget(self.groupBox_further_options, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.validation_finished)
        self.label_5.setMaximumSize(QtCore.QSize(131, 131))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/analysis-status-dialog/analysis_finished.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.validation_finished)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.frame_validation_error = QtWidgets.QFrame(validationStatusDialog)
        self.frame_validation_error.setEnabled(True)
        self.frame_validation_error.setStyleSheet("background-color: rgba(164, 219, 255, 235);")
        self.frame_validation_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_validation_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_validation_error.setObjectName("frame_validation_error")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_validation_error)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_validation_error = QtWidgets.QLabel(self.frame_validation_error)
        self.icon_validation_error.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_validation_error.setText("")
        self.icon_validation_error.setPixmap(QtGui.QPixmap(":/transformation-status-dialog/ic_info_black_48dp.png"))
        self.icon_validation_error.setScaledContents(True)
        self.icon_validation_error.setWordWrap(False)
        self.icon_validation_error.setObjectName("icon_validation_error")
        self.horizontalLayout_2.addWidget(self.icon_validation_error)
        self.label_validation_error = QtWidgets.QLabel(self.frame_validation_error)
        self.label_validation_error.setScaledContents(True)
        self.label_validation_error.setWordWrap(True)
        self.label_validation_error.setObjectName("label_validation_error")
        self.horizontalLayout_2.addWidget(self.label_validation_error)
        self.toolButton_validation_error_show_log = QtWidgets.QToolButton(self.frame_validation_error)
        self.toolButton_validation_error_show_log.setAutoFillBackground(False)
        self.toolButton_validation_error_show_log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolButton_validation_error_show_log.setObjectName("toolButton_validation_error_show_log")
        self.horizontalLayout_2.addWidget(self.toolButton_validation_error_show_log)
        self.gridLayout_3.addWidget(self.frame_validation_error, 1, 0, 1, 1)

        self.retranslateUi(validationStatusDialog)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox_close_status_dialog.accepted.connect(validationStatusDialog.accept)
        self.buttonBox_close_status_dialog.rejected.connect(validationStatusDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(validationStatusDialog)

    def retranslateUi(self, validationStatusDialog):
        _translate = QtCore.QCoreApplication.translate
        validationStatusDialog.setWindowTitle(_translate("validationStatusDialog", "Validierung"))
        self.label_2.setText(_translate("validationStatusDialog", "Validierung läuft ..."))
        self.pushButton_cancel_validation_process.setText(_translate("validationStatusDialog", "Abbrechen"))
        self.label_4.setText(_translate("validationStatusDialog", "Validierung abgeschlossen."))
        self.label_6.setText(_translate("validationStatusDialog", "Benötigte Zeit: "))
        self.label_validation_duration.setText(_translate("validationStatusDialog", "TextLabel"))
        self.groupBox_further_options.setTitle(_translate("validationStatusDialog", "Validierungsergebnisse verfügbar"))
        self.pushButton_open_validation_results.setText(_translate("validationStatusDialog", "Ergebnisse einblenden"))
        self.label_validation_error.setText(_translate("validationStatusDialog", "Die Validierung konnte nicht vollständig durchgeführt werden."))
        self.toolButton_validation_error_show_log.setText(_translate("validationStatusDialog", "Logdatei anzeigen"))

from gui_components.ui_templates import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    validationStatusDialog = QtWidgets.QDialog()
    ui = Ui_validationStatusDialog()
    ui.setupUi(validationStatusDialog)
    validationStatusDialog.show()
    sys.exit(app.exec_())
